version: '3'

services:
  node1:
    image: funkypenguin/bytechcoin
    container_name: bytechtest-node1
    volumes:
      - ../bytechcoind:/var/lib/bytechcoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/bytechcoin
#    container_name: bytechtest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/bytechcoin
#    container_name: bytechtest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

